// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_Resume.Context;

namespace Test_Resume.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Test_Resume.Model.ElementGraph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DominateLevel");

                    b.Property<int?>("ElementGraphId");

                    b.Property<DateTime?>("EndTime");

                    b.Property<string>("Name");

                    b.Property<DateTime?>("StartTime");

                    b.HasKey("Id");

                    b.HasIndex("ElementGraphId");

                    b.ToTable("ElementGraphs");
                });

            modelBuilder.Entity("Test_Resume.Model.ElementGraph", b =>
                {
                    b.HasOne("Test_Resume.Model.ElementGraph")
                        .WithMany("Childs")
                        .HasForeignKey("ElementGraphId");
                });
#pragma warning restore 612, 618
        }
    }
}
